subtask: 'single_obj'
env_file: "/home/sdur/Planning/Codes/basenet/isaac_envs/task.usd"
mdp:
  gamma: 1
  horizon: 1
  reward:
    task_success: 100000
  navigation:
    max_tran_speed: 0.5
    max_rot_speed: 0.5
  manipulation:
    max_rot_speed: 0.25
  table_dimensions:
    x_min:  -0.4
    x_max:  0.4
    y_min: -1.0
    y_max:  1.0
  safe_dist_from_table: 0.1
  max_dist_from_table: 0.3
  obj_safety_distance: 0.1
  render: False
train:
  initial_replay_size: 4500
  max_replay_size: 100000
  batch_size: 128
  n_features: 256
  warmup_transitions: 4500
  tau: 0.005
  n_steps_per_fit: 1
  lr_alpha: 3e-4
  lr_actor: 3e-4 
  lr_critic: 3e-4 
  target_entropy: -6
  n_epochs: 200
  n_steps_train: 4500
  n_steps_test: 500
  save_dir: '/home/sdur/Planning/Data/BaSeNet'
test:
  save_dir: '/home/sdur/Planning/Data/BaSeNet'
  agent_name: 'optimize_base_pose_SAC_epoch_1000'
  n_episodes: 5000
  n_steps: 5000
  save_data: True

